openapi: '3.0.2'
info:
  title: Snake
  version: '1.0'
servers:
  - url: http://localhost:3000/v1
tags:
  - name: User

components:
  schemas:
    user:
      type: object
      properties:
        username:
          type: string
        fullname:
          type: string  
        email: 
          type: string
          format: email
        password:
          type: string
          format: password
paths:
  /users:
    get:
      summary: Obtiene el listado de Usuarios
      operationId: gerUsers
      responses:
        '200':
          description: OK
          content:
            aplication/json:
              schema:
               type: array
               items:
                $ref: "#components/schemas/user"
      tags:
          - "User" 

  /users/new:
    post:
      summary: Creacion de un usuario
      operationId: postUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:          # <!--- form field name
                  type: string
                fullname:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
      responses: 
        '201':
          description: OK
          content:
           application/json:
              schema:
               $ref: "#components/schemas/user"
                     
      tags:
          - "User"    
          
  /users/{id}:
    get: 
      summary: Obtiene un solo Usuario
      parameters:
        - name: id
          in: path
          required: true
          description: Parametro de usuario
          schema: 
            type: string
      responses:
        '200':
          description: OK   
          content:
            application/json:
               schema:
                $ref: "#components/schemas/user"
      tags:
          - "User"           
  

        